const Homeproduct =
[
    {
        id: 1,
        Name: 'product1',
        price: '150',
        image: 'image/Best Buy_ ASUS 15_6_ 4K Ultra HD Touch-Screen Laptop Intel Core i9 16GB Memory NVIDIA GeForce GTX 1050 Ti 512GB SSD Deep Blue Ocean UX580GEXB74T.jpeg',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 2,
        Name: 'product2',
        price: '140',
        image: 'image/2d04916c-25cc-44e4-90f3-7d21ba18e9fd.jpeg',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 3,
        Name: 'product3',
        price: '236',
        image: 'image/67e9b14b-b5a4-4e31-86cc-8bed9a13899e.jpeg',
        cat: 'laptoo',
        type: 'new',
    },
    {
        id: 4,
        Name: 'product4',
        price: '336',
        image: 'image/Best Mini Laptops in 2021 _ Extremely Portable and Compact.jpeg',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 5,
        Name: 'product5',
        price: '198',
        image: 'image/Lenovo laptop, very long lasting_.jpeg',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 6,
        Name: 'product6',
        price: '259',
        image: 'image/Les meilleurs PC portables en mars 2024 - CNET France.jpeg',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 7,
        Name: 'product7',
        price: '956',
        image: 'image/Acer Aspire 3 Intel Core i5 11th Gen (12 GB_512GB SSD_Windows 11 Home_MS Office_1_7 Kg_Silver) A315-58 with 15.6-inch (39.6 cms) Full HD Display Laptop.6 cms) Full HD Display Laptop.6 cms) Full HD Display Laptop',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 8,
        Name: 'product8',
        price: '389',
        image: 'image/Cheap Laptops _ Computers _ Woot.jpeg',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 9,
        Name: 'product9',
        price: '167',
        image: 'image/Top 5 laptop dưới 10 triệu bán chạy nhất trên thị trường hiện nay.jpeg',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 10,
        Name: 'product10',
        price: '276',
        image: 'image/WhatsApp Image 2024-04-04 at 1.44.47 AM.jpeg',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 11,
        Name: 'product11',
        price: '187',
        image: 'image/Wm6 Lenovo 11_6_ 100e Celeron N3350 4_32gb 81er, Black.jpeg',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 12,
        Name: 'product12',
        price: '507',
        image: 'image/WhatsApp Image 2024-04-04 at 1.44.48 AM.jpeg',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 13,
        Name: 'product13',
        price: '250',
        image: 'image/Best Buy_ ASUS 15_6_ 4K Ultra HD Touch-Screen Laptop Intel Core i9 16GB Memory NVIDIA GeForce GTX 1050 Ti 512GB SSD Deep Blue Ocean UX580GEXB74T.jpeg',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 14,
        Name: 'product14',
        price: '340',
        image: 'image/Best Buy_ ASUS ROG G531GT 15_6_ Gaming Laptop Intel Core i7 8GB Memory NVIDIA GeForce GTX 1650 512GB Solid State Drive Black G531GT-BI7N6.jpeg',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 15,
        Name: 'product15',
        price: '236',
        image: 'image/Best Mini Laptops in 2021 _ Extremely Portable and Compact.jpeg',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 16,
        Name: 'product16',
        price: '336',
        image: 'image/Best Laptop For Travelers 2019 - How to Choose the Best Travel Laptop.jpeg',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 17,
        Name: 'product17',
        price: '298',
        image: 'image/HP 15s-11th Gen Intel Core i3 15_6 Laptop (8GB RAM_512GB SSD, FHD, Micro-Edge, Anti-Glare Dis___.jpeg',
        cat: 'laptop',
        type: 'new'
    },
    {
        id: 18,
        Name: 'product18',
        price: '159',
        image: 'image/Cheap Laptops _ Computers _ Woot.jpeg',
        cat: 'laptop',
        type: 'new'
    },
    {
        id: 19,
        Name: 'product19',
        price: '456',
        image: 'image/Lenovo IdeaPad 3 Intel Core i3-1115G4 11th Gen 15_6 FHD.jpeg',
        cat: 'laptop',
        type: 'new'
    },
    {
        id: 20,
        Name: 'product20',
        price: '389',
        image: 'image/Lenovo IdeaPad 3i 15_6_ Full HD Touchscreen Laptop, Intel Core i5-1155G7, 8GB RAM, 512GB SSD, Windows 11 Home, Abyss Blue.jpeg',
        cat: 'laptop',
        type: 'new'
    
    },
    {
        id: 21,
        Name: 'product21',
        price: '167',
        image: 'image/MacBook.jpeg',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 22,
        Name: 'product22',
        price: '176',
        image: 'image/Top 5 laptop dưới 10 triệu bán chạy nhất trên thị trường hiện nay.jpeg',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 23,
        Name: 'product23',
        price: '187',
        image: 'image/fca69f3a-4740-404d-b0d5-ea5cc995804e.jpeg',
        cat: 'laptop',
        type: 'new',
    },
    {
        id: 24,
        Name: 'product24',
        price: '407',
        image: 'image/Refurbished Electronics_ LCD TV, Digital Cameras, Laptops & more at TechForLess - Satisfaction Guaranteed.jpeg',
        cat: 'laptop',
        type: 'new',
    }
]
export default Homeproduct